### ISSUE TITLE
I got index out of range when I ready to transfer to keyhelp

### ISSUE THREAD

**Issue by akong77** [TheCry/i-mscp-keyhelp-migration#7]
Hello,
When I transfer from imscp to keyhelp.
I got error message.

Found domain: horizoninn.com.tw
Get i-MSCP domain dns data
Traceback (most recent call last):
  File "/root/i-mscp-keyhelp-migration/./i-mscp_keyhelp_migration.py", line 194, in <module>
    while not imscpInputData.getImscpUserWebData(input("Enter the i-MSCP user name (first domain): "), client):
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 165, in getImscpUserWebData
    self.__getImscpDomainDns(self.imscpData['iUsernameDomainId'], self.imscpData['iUsernameDomainIdna'],
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 614, in __getImscpDomainDns
    self.imscpDnsEntries[index]['iDomainDnsEntryTTL'] = DomainDnsEntriesData[1].rstrip()
IndexError: list index out of range

What's this problem?

**Comment by TheCry** [comment]
There is a wrong entry in the DNS table. Check the DNS table of the customer domains
