### ISSUE TITLE
Contacts with polish characters

### ISSUE THREAD

**Issue by theqkash** [TheCry/i-mscp-keyhelp-migration#8]
Hello,

If there are any contacts with name or vcard in roundcube database with one of polish national characters  "ó", the roundcube contacts checking procedure ends with:

```
Traceback (most recent call last):
  File "/root/i-mscp-keyhelp-migration/./i-mscp_keyhelp_migration.py", line 194, in <module>
    while not imscpInputData.getImscpUserWebData(input("Enter the i-MSCP user name (first domain): "), client):
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 174, in getImscpUserWebData
    self.__getImscpDomainEmailaddresses(self.imscpData['iUsernameDomainId'],
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 998, in __getImscpDomainEmailaddresses
    self.__getImscpRoundcubeUsers(client, self.imscpDomainEmailAddressNormal[index]['iEmailAddress'])
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 1474, in __getImscpRoundcubeUsers
    self.__getImscpRoundcubeContacts(self.imscpRoundcubeUsers[index]['rUserId'], client)
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 1577, in __getImscpRoundcubeContacts
    for line in stdout:
  File "/usr/lib/python3/dist-packages/paramiko/file.py", line 125, in __next__
    line = self.readline()
  File "/usr/lib/python3/dist-packages/paramiko/file.py", line 334, in readline
    return line if self._flags & self.FLAG_BINARY else u(line)
  File "/usr/lib/python3/dist-packages/paramiko/py3compat.py", line 161, in u
    return s.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 120: invalid continuation byte
```

If I remove those manually, it works correctly.

Edit: The same is happening if there is any "ó" letter in any identity or user-related data in roundcube db.

Even if I fix "ó" it becomes an error with other polish symbols later, when inserting identity or contacts to database.

btw. Great job anyway. Except this one it is working perfectly!

**Comment by theqkash** [comment]
Got another:

```
Get i-MSCP roundcube domain email contact data
Traceback (most recent call last):
  File "/root/i-mscp-keyhelp-migration/./i-mscp_keyhelp_migration.py", line 194, in <module>
    while not imscpInputData.getImscpUserWebData(input("Enter the i-MSCP user name (first domain): "), client):
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 174, in getImscpUserWebData
    self.__getImscpDomainEmailaddresses(self.imscpData['iUsernameDomainId'],
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 998, in __getImscpDomainEmailaddresses
    self.__getImscpRoundcubeUsers(client, self.imscpDomainEmailAddressNormal[index]['iEmailAddress'])
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 1474, in __getImscpRoundcubeUsers
    self.__getImscpRoundcubeContacts(self.imscpRoundcubeUsers[index]['rUserId'], client)
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 1577, in __getImscpRoundcubeContacts
    for line in stdout:
  File "/usr/lib/python3/dist-packages/paramiko/file.py", line 125, in __next__
    line = self.readline()
  File "/usr/lib/python3/dist-packages/paramiko/file.py", line 334, in readline
    return line if self._flags & self.FLAG_BINARY else u(line)
  File "/usr/lib/python3/dist-packages/paramiko/py3compat.py", line 161, in u
    return s.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 39: invalid continuation byte
```

Again, "ó" here. It looks like utf-8 is working weird here.

**Comment by TheCry** [comment]
Hi.. I'm not able to test this. So you have to edit your file "_imscp.py"
Search line 1577:
`for line in stdout:`

modify to:
`for line in stdout.encode('utf-8'):`
or
`for line.encode('utf-8') in stdout:`

**Comment by theqkash** [comment]
It makes it doesn't work at all :-( 
Change 1:
```Traceback (most recent call last):
  File "/root/i-mscp-keyhelp-migration/./i-mscp_keyhelp_migration.py", line 194, in <module>
    while not imscpInputData.getImscpUserWebData(input("Enter the i-MSCP user name (first domain): "), client):
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 174, in getImscpUserWebData
    self.__getImscpDomainEmailaddresses(self.imscpData['iUsernameDomainId'],
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 998, in __getImscpDomainEmailaddresses
    self.__getImscpRoundcubeUsers(client, self.imscpDomainEmailAddressNormal[index]['iEmailAddress'])
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 1474, in __getImscpRoundcubeUsers
    self.__getImscpRoundcubeContacts(self.imscpRoundcubeUsers[index]['rUserId'], client)
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 1577, in __getImscpRoundcubeContacts
    for line in stdout.encode('utf-8'):
AttributeError: 'ChannelFile' object has no attribute 'encode'
```

Change 2:
```Traceback (most recent call last):
  File "/root/i-mscp-keyhelp-migration/./i-mscp_keyhelp_migration.py", line 184, in <module>
    from _imscp import imscpGetData
  File "/root/i-mscp-keyhelp-migration/_imscp.py", line 1577
    for line.encode('utf-8') in stdout:
        ^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot assign to function call
```

**Comment by TheCry** [comment]
I'd sent you an email. The problem come with the python module "paramiko":
https://github.com/paramiko/paramiko/issues/707#issuecomment-1951185314

**Comment by clusterx** [comment]
Is there already a working solution to solve this issue?
I guess the problem also occurs with other languages e.g. French special characters.

**Comment by theqkash** [comment]
Yes.

I've found the solution, with great help of @TheCry :

```
for line in stdout:
```

in __getImscpRoundcubeIdentities and __getImscpRoundcubeContacts functions in _imscp.py needs to be changed for:


```        
        stdout._set_mode("rb")
        for line in stdout:
            line = line.decode('utf-8',  'ignore')
```


Location:

https://github.com/TheCry/i-mscp-keyhelp-migration/blob/master/_imscp.py#L1501
https://github.com/TheCry/i-mscp-keyhelp-migration/blob/master/_imscp.py#L1577

Then it works like a charm.

Thank you @TheCry for your great help, and for great job at all!

**Comment by TheCry** [comment]
Thanks for the fix. I will test it lokal and add to the repo if it's working
